### ISSUE TITLE
PA Review: Registration / Tickets

### ISSUE THREAD

**Issue by cyl47** [cylinda47/eventize#3]

**Comment by LochandQuay** [comment]
@cylinda47 

- [x] Hate to say it, but you should probably have tickets pre-filled in when you go to edit the event. Otherwise you can't delete the tickets or edit them after you've created the event.
- [x] Can never delete the first ticket, even if you have other tickets. I feel like if you have multiple tickets, you should be able to delete the first one.
- [x] After clicking confirm on ticket order, nothing happens. Looks like the order was created, but modal doesn't close nor is there any redirect or anything.
- [x] No errors when selecting no ticket quantities. 
- [x] On ticket order, should list the number of remaining tickets available.

Styling is gorgeous!

**Comment by cyl47** [comment]
@LochandQuay 

- For my simple app, organizers wont be allowed to add extra / edit / delete existing tickets, as this involves refunding to ticket purchaser. Ticket creation section is removed from Event edit form.
- Ticket ordering bugs fixed. If there is no quantities selected users will be redirected to first page.
